git clone https://github.com/19balazs86/AzureFunctions.git
git clone https://github.com/19balazs86/index.git
git clone https://github.com/19balazs86/PlayingWithBenchmarkDotNet.git
git clone https://github.com/19balazs86/PlayingWithAggregateException.git
git clone https://github.com/19balazs86/PlayingWithDistributedCaching.git
git clone https://github.com/19balazs86/PlayingWithDistributedLock.git
git clone https://github.com/19balazs86/PlayingWithDistributedTracing.git
git clone https://github.com/19balazs86/PlayingWithGenericHost.git
git clone https://github.com/19balazs86/PlayingWithGraphQL.git
git clone https://github.com/19balazs86/PlayingWithHealthChecks.git
git clone https://github.com/19balazs86/PlayingWithHttpClientFactory.git
git clone https://github.com/19balazs86/Playing-with-JWT-Authentication.git
git clone https://github.com/19balazs86/PlayingWithMediatR.git
git clone https://github.com/19balazs86/PlayingWithMetrics.git
git clone https://github.com/19balazs86/PlayingWithMongoDB.git
git clone https://github.com/19balazs86/PlayingWithObserver.git
git clone https://github.com/19balazs86/PlayingWithOcelot.git
git clone https://github.com/19balazs86/PlayingWithRabbitMQ.git
git clone https://github.com/19balazs86/PlayingWithRefit.git
git clone https://github.com/19balazs86/Playing-with-Serilog.git
git clone https://github.com/19balazs86/PlayingWithSignalR.git
git clone https://github.com/19balazs86/PlayingWithSwagger.git
git clone https://github.com/19balazs86/PlayingWithTestHost.git
git clone https://github.com/19balazs86/ProjectUpdaterTool.git
pause