git clone https://github.com/19balazs86/AzureAppInsights.git
git clone https://github.com/19balazs86/AzureContainerApp.git
git clone https://github.com/19balazs86/AzureCosmosDB
git clone https://github.com/19balazs86/AzureDevOps.git
git clone https://github.com/19balazs86/AzureEventGrid.git
git clone https://github.com/19balazs86/AzureEventHubs.git
git clone https://github.com/19balazs86/AzureFunctions.git
git clone https://github.com/19balazs86/AzureServiceBus.git
git clone https://github.com/19balazs86/AzureStaticWebAppBlazorPolling
git clone https://github.com/19balazs86/index.git
git clone https://github.com/19balazs86/PlayingWith_gRPC.git
git clone https://github.com/19balazs86/PlayingWithAggregateException.git
git clone https://github.com/19balazs86/PlayingWithAuthentication.git
git clone https://github.com/19balazs86/PlayingWithBenchmarkDotNet.git
git clone https://github.com/19balazs86/PlayingWithDapr.git
git clone https://github.com/19balazs86/PlayingWithDeviceOfflineDetection.git
git clone https://github.com/19balazs86/PlayingWithDistributedLock.git
git clone https://github.com/19balazs86/PlayingWithGenerativeAI.git
git clone https://github.com/19balazs86/PlayingWithGenericHost.git
git clone https://github.com/19balazs86/PlayingWithGraphQL.git
git clone https://github.com/19balazs86/PlayingWithHangfire.git
git clone https://github.com/19balazs86/PlayingWithHealthChecks.git
git clone https://github.com/19balazs86/PlayingWithHttpClientFactory.git
git clone https://github.com/19balazs86/PlayingWithMediatR.git
git clone https://github.com/19balazs86/PlayingWithMongoDB.git
git clone https://github.com/19balazs86/PlayingWithMountebank.git
git clone https://github.com/19balazs86/PlayingWithOcelot.git
git clone https://github.com/19balazs86/PlayingWithOpenTelemetry
git clone https://github.com/19balazs86/PlayingWithOrleans.git
git clone https://github.com/19balazs86/PlayingWithRabbitMQ.git
git clone https://github.com/19balazs86/PlayingWithRefit.git
git clone https://github.com/19balazs86/PlayingWithRxDotNet.git
git clone https://github.com/19balazs86/PlayingWithSagaPattern.git
git clone https://github.com/19balazs86/Playing-with-Serilog.git
git clone https://github.com/19balazs86/PlayingWithSignalR.git
git clone https://github.com/19balazs86/PlayingWithSwagger.git
git clone https://github.com/19balazs86/PlayingWithTestContainers.git
git clone https://github.com/19balazs86/PlayingWithTestHost.git
git clone https://github.com/19balazs86/PlayingWithWolverineMarten.git
git clone https://github.com/19balazs86/PlayingWithYARP.git
git clone https://github.com/19balazs86/ProjectUpdaterTool.git
pause